export const constants={
    REQUEST: 'REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOADING_MAIN: 'LOADING_MAIN',
    SET_TITLE:'SET_TITLE',
    USER_LOADING_SUCCESS: 'USER_LOADING_SUCCESS',
    UPLINE_LOAD_SUCCESS:'UPLINE_LOAD_SUCCESS',
    DASHBOARD_LOAD_SUCCESS:'DASHBOARD_LOAD_SUCCESS',
    SET_FIREBASE_TOKEN:'SET_FIREBASE_TOKEN',
    //Template changes
    MENU_CHANGE:'MENU_CHANGE',
    //App changes
    SET_ADDCLICK:'SET_ADDCLICK',
    SHOW_ADD:'SHOW_ADD',
    SET_STATUS_LIST:'SET_STATUS_LIST'
}